package:
  name: peer-mgmt-service
  version: "0.0.0"
  epoch: 0
  description: peer-mgmt-service — OP Stack peer management service
  copyright:
    - license: MIT

environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
    packages:
      - busybox
      - ca-certificates-bundle
      - go-1.26
  environment:
    CGO_ENABLED: "1"

pipeline:
  - uses: go/build
    with:
      modroot: peer-mgmt-service
      packages: ./cmd/pms
      output: pms
      go-package: go-1.26
      ldflags: -s -w

  - uses: app-compat/install-to-app
    with:
      binary-name: pms

  - uses: strip
