package:
  name: proxyd
  version: "0.0.0"
  epoch: 0
  description: proxyd — OP Stack RPC request router and proxy
  copyright:
    - license: MIT

environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
    packages:
      - busybox
      - ca-certificates-bundle
      - go-1.26
  environment:
    CGO_ENABLED: "1"
    GITCOMMIT: "melange"
    GITDATE: "0"

pipeline:
  - uses: go/build
    with:
      modroot: proxyd
      packages: ./cmd/proxyd
      output: proxyd
      go-package: go-1.26
      ldflags: -s -w -X main.GitVersion=${{package.version}} -X main.GitCommit=$GITCOMMIT -X main.GitDate=$GITDATE

  - uses: strip
