
version: 2.1
workflows:
  logging:
    jobs:
      - log-tag-results
  release:
    when:
      not:
        equal: [ scheduled_pipeline, << pipeline.trigger_source >> ]
    jobs:
      - hold:
          type: approval
          filters:
            tags:
              only: /^(proxyd|ufm-[a-z0-9\-]*|op-[a-z0-9\-]*)\/v.*/
            branches:
              ignore: /.*/
      - docker-build:
          name: op-ufm-docker-build
          filters:
            tags:
              only: /^op-ufm\/v.*/
            branches:
              ignore: /.*/
          docker_name: op-ufm
          docker_tags: <<pipeline.git.revision>>
          docker_context: .
          docker_file: op-ufm/Dockerfile
          context:
            - oplabs-gcr-release
          requires:
            - hold
      - docker-publish:
          name: op-ufm-docker-publish
          docker_name: op-ufm
          docker_tags: <<pipeline.git.revision>>
          context:
            - oplabs-gcr
          requires:
            - op-ufm-docker-build

      - docker-build:
          name: proxyd-docker-build
          filters:
            tags:
              only: /^proxyd\/v.*/
            branches:
              ignore: /.*/
          docker_name: proxyd
          docker_tags: <<pipeline.git.revision>>
          docker_context: .
          docker_file: proxyd/Dockerfile
          context:
            - oplabs-gcr-release
          requires:
            - hold
      - docker-publish:
          name: proxyd-docker-release
          filters:
            tags:
              only: /^proxyd\/v.*/
            branches:
              ignore: /.*/
          docker_name: proxyd
          docker_tags: <<pipeline.git.revision>>
          context:
            - oplabs-gcr-release
          requires:
            - proxyd-docker-build

      - docker-build:
          name: op-conductor-mon-docker-build
          docker_file: op-conductor-mon/Dockerfile
          docker_name: op-conductor-mon
          docker_tags: <<pipeline.git.revision>>,<<pipeline.git.branch>>
          docker_context: .
          requires:
            - hold
      - docker-publish:
          name: op-conductor-mon-docker-publish
          docker_name: op-conductor-mon
          docker_tags: <<pipeline.git.revision>>,<<pipeline.git.branch>>
          context:
            - oplabs-gcr
          requires:
            - op-conductor-mon-docker-build
