// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ethereum-optimism/infra/op-signer/provider (interfaces: GCPKMSClient)

// Package provider is a generated GoMock package.
package provider

import (
	context "context"
	reflect "reflect"

	kmspb "cloud.google.com/go/kms/apiv1/kmspb"
	gomock "github.com/golang/mock/gomock"
	gax "github.com/googleapis/gax-go/v2"
)

// MockGCPKMSClient is a mock of GCPKMSClient interface.
type MockGCPKMSClient struct {
	ctrl     *gomock.Controller
	recorder *MockGCPKMSClientMockRecorder
}

// MockGCPKMSClientMockRecorder is the mock recorder for MockGCPKMSClient.
type MockGCPKMSClientMockRecorder struct {
	mock *MockGCPKMSClient
}

// NewMockGCPKMSClient creates a new mock instance.
func NewMockGCPKMSClient(ctrl *gomock.Controller) *MockGCPKMSClient {
	mock := &MockGCPKMSClient{ctrl: ctrl}
	mock.recorder = &MockGCPKMSClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGCPKMSClient) EXPECT() *MockGCPKMSClientMockRecorder {
	return m.recorder
}

// AsymmetricSign mocks base method.
func (m *MockGCPKMSClient) AsymmetricSign(arg0 context.Context, arg1 *kmspb.AsymmetricSignRequest, arg2 ...gax.CallOption) (*kmspb.AsymmetricSignResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AsymmetricSign", varargs...)
	ret0, _ := ret[0].(*kmspb.AsymmetricSignResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AsymmetricSign indicates an expected call of AsymmetricSign.
func (mr *MockGCPKMSClientMockRecorder) AsymmetricSign(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AsymmetricSign", reflect.TypeOf((*MockGCPKMSClient)(nil).AsymmetricSign), varargs...)
}

// GetPublicKey mocks base method.
func (m *MockGCPKMSClient) GetPublicKey(arg0 context.Context, arg1 *kmspb.GetPublicKeyRequest, arg2 ...gax.CallOption) (*kmspb.PublicKey, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetPublicKey", varargs...)
	ret0, _ := ret[0].(*kmspb.PublicKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPublicKey indicates an expected call of GetPublicKey.
func (mr *MockGCPKMSClientMockRecorder) GetPublicKey(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPublicKey", reflect.TypeOf((*MockGCPKMSClient)(nil).GetPublicKey), varargs...)
}
