# TODO: just is not working as we depend on go.just
#
#
# import '../justfiles/go.just'
#
# Build ldflags string
# _LDFLAGSSTRING := "'" + trim(
#     "-X main.GitCommit=" + GITCOMMIT + " " + \
#     "-X main.GitDate=" + GITDATE + " " + \
#     "-X main.Version=" + VERSION + " " + \
#     "") + "'"

BINARY := "./bin/op-nat"

all: build

docker:
	docker build ../ -f Dockerfile -t op-nat:latest

# Build op-nat binary
# op-nat: (go_build BINARY "./cmd" "-ldflags" _LDFLAGSSTRING)
build:
    CGO_ENABLED=0 go build -o ./bin/op-nat ./cmd

# Clean build artifacts
clean:
    rm -f {{BINARY}}

# Run tests
# test: (go_test "./...")
test:
    CGO_ENABLED=0 go build ./... && go test -count=1 -v ./...

# Run prometheus and grafana
start-monitoring:
    docker compose -f 'docker-compose.yml' up -d --build

# Stop prometheus and grafana
stop-monitoring:
    docker compose -f 'docker-compose.yml' down
