{
 "title": "Public dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "network",
    "query": {
     "query": "label_values(op_gasPrice, cluster)"
    }
   },
   { "name": "prometheus_replica", "query": "${VAR_PROMETHEUS_REPLICA}" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "- All times are in your local timezone\n- The layer 2 gas price is normally 0.001 gwei, but it increases when experiencing heavy congestion\n- The layer 1 gas price is relevant because it affects the price of writing the transaction data (we are a rollup, not a sidechain)"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Endpoint Uptime",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "probe_success{probe=~\".*\",instance=\"https://$network.optimism.io\", job=\"$network endpoint\"}",
     "legendFormat": "{{ probe }}"
    }
   ]
  },
  {
   "title": "Layer2 Gas Price",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (layer) (op_gasPrice{cluster=~\"$network.*\", layer=\"layer2\", prometheus_replica=\"prometheus-k8s-0\"} ) * 10^-9"
    }
   ]
  },
  {
   "title": "Layer2 Gas Price History",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 3 },
   "targets": [
    {
     "expr": "sum by (layer) (op_gasPrice{cluster=~\"$network.*\", layer=\"layer2\", prometheus_replica=\"prometheus-k8s-0\"})  * 10^-9",
     "legendFormat": "{{ layer }}"
    }
   ]
  },
  {
   "title": "Transactions per 10 minutes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (cluster) (increase(op_blocknumber{cluster=~\"$network.*\", prometheus_replica=\"prometheus-k8s-0\"}[10m]))",
     "legendFormat": "{{ network }}"
    }
   ]
  },
  {
   "title": "Layer1 Gas Price",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (layer) (op_gasPrice{cluster=~\"$network.*\", layer=\"layer1\", prometheus_replica=\"prometheus-k8s-0\"})  * 10^-9",
     "legendFormat": "{{ layer }}"
    }
   ]
  },
  {
   "title": "Layer1 Gas Price History",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "sum by (layer) (op_gasPrice{cluster=~\"$network.*\", layer=\"layer1\", prometheus_replica=\"prometheus-k8s-0\"})  * 10^-9",
     "legendFormat": "{{ layer }}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 13 },
   "options": {
    "content": "# Uniswap trade\n\nAssuming the following\n- L1 gas == 10k\n- L2 gas == 2m\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\nsum by (cluster) (op_gasPrice{layer=\"layer1\", cluster=~\"$network.*\", prometheus_replica=\"prometheus-k8s-0\"} * 10^4 ) +\n  ignoring(layer)\nsum by (cluster) (op_gasPrice{layer=\"layer2\", cluster=~\"$network.*\", prometheus_replica=\"prometheus-k8s-0\"} * 2 * 10^6 )\n)\n* 1.5 * 10^-18\n* ignoring (endpoint,instance,job,namespace,network,pod,service,prometheus_replica,prometheus) \nethusd{cluster=~\"$network.*\",prometheus_replica=\"prometheus-k8s-0\"}"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "(\nsum by (cluster) (op_gasPrice{layer=\"layer1\", cluster=~\"$network.*\", prometheus_replica=\"prometheus-k8s-0\"} * 10^4 ) +\n  ignoring(layer)\nsum by (cluster) (op_gasPrice{layer=\"layer2\", cluster=~\"$network.*\", prometheus_replica=\"prometheus-k8s-0\"} * 2 * 10^6 )\n)\n* 1.5 * 10^-18\n* ignoring (endpoint,instance,job,namespace,network,pod,service,prometheus_replica,prometheus) \nethusd{cluster=~\"$network.*\",prometheus_replica=\"prometheus-k8s-0\"}",
     "legendFormat": "Uniswap trade"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 19 },
   "options": {
    "content": "# ETH transfer\n\nAssuming the following\n- L1 gas == 2.85k\n- L2 gas == 1m\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\nsum by (cluster) (op_gasPrice{layer=\"layer1\", cluster=~\"$network.*\", prometheus_replica=\"prometheus-k8s-0\"} * 2850 ) +\n  ignoring(layer)\nsum by (cluster) (op_gasPrice{layer=\"layer2\", cluster=~\"$network.*\", prometheus_replica=\"prometheus-k8s-0\"} * 1 * 10^6 )\n)\n* 1.5 * 10^-18\n* ignoring (endpoint,instance,job,namespace,network,pod,service,prometheus_replica,prometheus) \nethusd{cluster=~\"$network.*\",prometheus_replica=\"prometheus-k8s-0\"}"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "(\nsum by (cluster) (op_gasPrice{layer=\"layer1\", cluster=~\"$network.*\", prometheus_replica=\"prometheus-k8s-0\"} * 2850 ) +\n  ignoring(layer)\nsum by (cluster) (op_gasPrice{layer=\"layer2\", cluster=~\"$network.*\", prometheus_replica=\"prometheus-k8s-0\"} * 1 * 10^6 )\n)\n* 1.5 * 10^-18\n* ignoring (endpoint,instance,job,namespace,network,pod,service,prometheus_replica,prometheus) \nethusd{cluster=~\"$network.*\",prometheus_replica=\"prometheus-k8s-0\"}",
     "legendFormat": "Uniswap trade"
    }
   ]
  }
 ]
}