# Log level.
# Possible values: trace | debug | info | warn | error | crit
# Default: debug
log_level = "debug"

[signer_service]
# URL to the signer service
url = "http://localhost:1234"
tls_ca_cert = "tls/ca.crt"
tls_cert = "tls/tls.crt"
tls_key = "tls/tls.key"

[healthz]
# Whether or not to enable healthz endpoint
enabled = true
# Host for the healthz endpoint to listen on
host = "0.0.0.0"
# Port for the above.
port = "8080"

[metrics]
# Whether or not to enable Prometheus metrics
enabled = true
# Host for the Prometheus metrics endpoint to listen on.
host = "0.0.0.0"
# Port for the above.
port = "9761"

[wallets.default]
# OP Stack Chain ID
# see https://community.optimism.io/docs/useful-tools/networks/
chain_id = 420
# Signer method to use
# Possible values: signer | static
signer_method = "static"
# Address used to send transactions
address = "0x0000000000000000000000000000000000000000"
# For static signer method, the private key to use
private_key = "0000000000000000000000000000000000000000000000000000000000000000"
# Transaction value in wei
tx_value = 100000000000000

[providers.p1]
# URL to the RPC provider
url = "http://localhost:8551"
# Read only providers are only used to check for transactions
read_only = true
# Interval to poll the provider for expected transactions
read_interval = "10s"
# Interval to submit new transactions to the provider
send_interval = "30s"
# Interval between send transaction when we get "already known" txpool err
send_transaction_retry_interval = "100ms"
# Max time to retry
send_transaction_retry_timeout = "5s"
# Interval between each send transaction to the same network
send_transaction_cool_down = "30s"
# Interval between receipt retrieval
receipt_retrieval_interval = "500ms"
# Max time to check for receipt
receipt_retrieval_timeout = "2m"

[providers.p2]
# Uncomment to disable this provider
# disabled=true
# URL to the RPC provider
url = "http://localhost:8552"
# Read only providers are only used to check for transactions
read_only = false
# Interval to poll the provider for expected transactions
read_interval = "10s"
# Interval to submit new transactions to the provider
send_interval = "30s"
# Interval between send transaction when we get "already known" txpool err
send_transaction_retry_interval = "100ms"
# Max time to retry
send_transaction_retry_timeout = "5s"
# Interval between each send transaction to the same network
send_transaction_cool_down = "30s"
# Interval between receipt retrieval
receipt_retrieval_interval = "500ms"
# Max time to check for receipt
receipt_retrieval_timeout = "2m"
