[server]
rpc_port = 10000

[backend]
response_timeout_seconds = 30

[backends]
[backends.main]
rpc_url = "http://127.0.0.1:8123"
ws_url = ""

[backend_groups]
[backend_groups.main]
backends = ["main"]

[rpc_method_mappings]
eth_blockNumber = "main"
eth_getBlockReceipts = "main"
eth_chainId = "main"
eth_call = "main"
eth_getBlockByNumber = "main"
eth_getLogs = "main"
eth_getBalance = "main"
eth_getCode = "main"
eth_getTransactionCount = "main"
eth_getTransactionReceipt = "main"
eth_sendRawTransaction = "main"
net_version = "main"
web3_clientVersion = "main"
