name: build images

on:
  push:
    branches:
      - 'main'
    tags:
      - '*/v*' # Match tags like proxyd/v1.2.3
      - 'v*'
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  plan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      matrix_json: ${{ steps.plan.outputs.matrix_json }}
      has_builds: ${{ steps.plan.outputs.has_builds }}
    steps:
      - name: Checkout
        uses: actions/checkout@71cf2267d89c5cb81562390fa70a37fa40b1305e # v6
        with:
          fetch-depth: 0
      - name: Plan
        id: plan
        uses: ethereum-optimism/factory/actions/plan@aced2657632c849ce64a84cc72e3d2940883d374

  build:
    needs: [plan]
    if: needs.plan.outputs.has_builds == 'true'
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.plan.outputs.matrix_json) }}
    uses: ethereum-optimism/factory/.github/workflows/docker.yaml@aced2657632c849ce64a84cc72e3d2940883d374
    with:
      image_name: ${{ matrix.image_name }}
      context: ${{ matrix.context }}
      dockerfile: ${{ matrix.dockerfile }}
      gcp_project_id: ${{ vars.GCP_PROJECT_ID_OPLABS_TOOLS_ARTIFACTS }}
      registry: us-docker.pkg.dev/oplabs-tools-artifacts/images
    permissions:
      contents: read
      id-token: write
      attestations: write
